// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refresh-token": {
            "post": {
                "description": "Refresh Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Token",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshTokenDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AuthResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/validate-google-id-token": {
            "post": {
                "description": "Validate Google ID Token (Login)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Validate Google ID Token",
                "parameters": [
                    {
                        "description": "Google ID Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ValidateGoogleIdTokenDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AuthResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/profile/my": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get My Profile Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Update My Profile Data",
                "parameters": [
                    {
                        "description": "Update User Profile",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserProfileDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/team/registration/cp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team Registration"
                ],
                "summary": "Register CP Team",
                "parameters": [
                    {
                        "description": "Register CP Team",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegistrationCPTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RegistrationCPTeamResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/team/registration/find/{join_code}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team Registration"
                ],
                "summary": "Find Team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Join Code",
                        "name": "join_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RegistraionTeamResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/team/registration/hackathon": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team Registration"
                ],
                "summary": "Register Hackathon Team",
                "parameters": [
                    {
                        "description": "Register Hackathon Team",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegistrationHackathonTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RegistrationHackathonTeamResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/team/registration/join/{join_code}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team Registration"
                ],
                "summary": "Join Team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Join Code",
                        "name": "join_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RegistraionTeamResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserResponseDTO"
                }
            }
        },
        "dto.RefreshTokenDTO": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.RegistraionTeamResponse": {
            "type": "object",
            "required": [
                "supervisor",
                "supervisor_nidn",
                "team_name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id_team": {
                    "type": "integer"
                },
                "supervisor": {
                    "type": "string"
                },
                "supervisor_nidn": {
                    "type": "string"
                },
                "team_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.RegistrationCPResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "domjudge_password": {
                    "type": "string"
                },
                "domjudge_username": {
                    "type": "string"
                },
                "id_cp_team": {
                    "type": "integer"
                },
                "id_team": {
                    "type": "integer"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "dto.RegistrationCPTeamRequest": {
            "type": "object",
            "required": [
                "supervisor",
                "supervisor_nidn",
                "team_name"
            ],
            "properties": {
                "supervisor": {
                    "type": "string"
                },
                "supervisor_nidn": {
                    "type": "string"
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "dto.RegistrationCPTeamResponse": {
            "type": "object",
            "properties": {
                "cpteam": {
                    "$ref": "#/definitions/dto.RegistrationCPResponse"
                },
                "team": {
                    "$ref": "#/definitions/dto.RegistraionTeamResponse"
                }
            }
        },
        "dto.RegistrationHackathonResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id_HackathonTeam": {
                    "type": "integer"
                },
                "id_team": {
                    "type": "integer"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.RegistrationHackathonTeamRequest": {
            "type": "object",
            "required": [
                "supervisor",
                "supervisor_nidn",
                "team_name"
            ],
            "properties": {
                "supervisor": {
                    "type": "string"
                },
                "supervisor_nidn": {
                    "type": "string"
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "dto.RegistrationHackathonTeamResponse": {
            "type": "object",
            "properties": {
                "hackathonTeam": {
                    "$ref": "#/definitions/dto.RegistrationHackathonResponse"
                },
                "team": {
                    "$ref": "#/definitions/dto.RegistraionTeamResponse"
                }
            }
        },
        "dto.UpdateUserProfileDTO": {
            "type": "object",
            "required": [
                "birth_date",
                "birth_place",
                "gender",
                "institusi",
                "name",
                "nim"
            ],
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "birth_place": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "institusi": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nim": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponseDTO": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "description": "BirthPlace string     ` + "`" + `json:\"birth_place\"` + "`" + `",
                    "type": "string"
                },
                "data_has_verified": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "institusi": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nim": {
                    "description": "Gender     string     ` + "`" + `json:\"gender\"` + "`" + `",
                    "type": "string"
                },
                "profile_has_updated": {
                    "type": "boolean"
                },
                "profile_picture": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.ValidateGoogleIdTokenDTO": {
            "type": "object",
            "required": [
                "google_id_token"
            ],
            "properties": {
                "google_id_token": {
                    "type": "string"
                }
            }
        },
        "helper.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1/gcw/resources",
	Schemes:          []string{},
	Title:            "GCW API",
	Description:      "This is a sample server for GCW API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
