basePath: /api/v1/gcw/resources
definitions:
  dto.AuthResponseDTO:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/dto.UserResponseDTO'
    type: object
  dto.RefreshTokenDTO:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RegistraionTeamResponse:
    properties:
      created_at:
        type: string
      id_team:
        type: integer
      supervisor:
        type: string
      supervisor_nidn:
        type: string
      team_name:
        type: string
      updated_at:
        type: string
    required:
    - supervisor
    - supervisor_nidn
    - team_name
    type: object
  dto.RegistrationCPResponse:
    properties:
      createdAt:
        type: string
      domjudge_password:
        type: string
      domjudge_username:
        type: string
      id_cp_team:
        type: integer
      id_team:
        type: integer
      stage:
        type: string
      status:
        type: string
      updatedAt:
        type: string
    type: object
  dto.RegistrationCPTeamRequest:
    properties:
      supervisor:
        type: string
      supervisor_nidn:
        type: string
      team_name:
        type: string
    required:
    - supervisor
    - supervisor_nidn
    - team_name
    type: object
  dto.RegistrationCPTeamResponse:
    properties:
      cpteam:
        $ref: '#/definitions/dto.RegistrationCPResponse'
      team:
        $ref: '#/definitions/dto.RegistraionTeamResponse'
    type: object
  dto.RegistrationHackathonResponse:
    properties:
      created_at:
        type: string
      id_HackathonTeam:
        type: integer
      id_team:
        type: integer
      stage:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  dto.RegistrationHackathonTeamRequest:
    properties:
      supervisor:
        type: string
      supervisor_nidn:
        type: string
      team_name:
        type: string
    required:
    - supervisor
    - supervisor_nidn
    - team_name
    type: object
  dto.RegistrationHackathonTeamResponse:
    properties:
      hackathonTeam:
        $ref: '#/definitions/dto.RegistrationHackathonResponse'
      team:
        $ref: '#/definitions/dto.RegistraionTeamResponse'
    type: object
  dto.UpdateUserProfileDTO:
    properties:
      birth_date:
        type: string
      birth_place:
        type: string
      gender:
        type: string
      institusi:
        type: string
      name:
        type: string
      nim:
        type: string
    required:
    - birth_date
    - birth_place
    - gender
    - institusi
    - name
    - nim
    type: object
  dto.UserResponseDTO:
    properties:
      birth_date:
        description: BirthPlace string     `json:"birth_place"`
        type: string
      data_has_verified:
        type: boolean
      email:
        type: string
      id:
        type: integer
      institusi:
        type: string
      major:
        type: string
      name:
        type: string
      nim:
        description: Gender     string     `json:"gender"`
        type: string
      profile_has_updated:
        type: boolean
      profile_picture:
        type: string
      role:
        type: string
    type: object
  dto.ValidateGoogleIdTokenDTO:
    properties:
      google_id_token:
        type: string
    required:
    - google_id_token
    type: object
  helper.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample server for GCW API.
  title: GCW API
  version: "1.0"
paths:
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh Token
      parameters:
      - description: Refresh Token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AuthResponseDTO'
              type: object
      summary: Refresh Token
      tags:
      - Auth
  /auth/validate-google-id-token:
    post:
      consumes:
      - application/json
      description: Validate Google ID Token (Login)
      parameters:
      - description: Google ID Token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ValidateGoogleIdTokenDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AuthResponseDTO'
              type: object
      summary: Validate Google ID Token
      tags:
      - Auth
  /profile/my:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserResponseDTO'
              type: object
      summary: Get My Profile Data
      tags:
      - Profile
    post:
      consumes:
      - application/json
      parameters:
      - description: Update User Profile
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserProfileDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserResponseDTO'
              type: object
      summary: Update My Profile Data
      tags:
      - Profile
  /team/registration/cp:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register CP Team
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegistrationCPTeamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RegistrationCPTeamResponse'
              type: object
      summary: Register CP Team
      tags:
      - Team Registration
  /team/registration/find/{join_code}:
    get:
      parameters:
      - description: Join Code
        in: query
        name: join_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RegistraionTeamResponse'
              type: object
      summary: Find Team
      tags:
      - Team Registration
  /team/registration/hackathon:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register Hackathon Team
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegistrationHackathonTeamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RegistrationHackathonTeamResponse'
              type: object
      summary: Register Hackathon Team
      tags:
      - Team Registration
  /team/registration/join/{join_code}:
    post:
      parameters:
      - description: Join Code
        in: query
        name: join_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RegistraionTeamResponse'
              type: object
      summary: Join Team
      tags:
      - Team Registration
swagger: "2.0"
